// <auto-generated />
using LearnAppServerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnAppServerAPI.Migrations
{
    [DbContext(typeof(LearnAppServerAPIContext))]
    partial class LearnAppServerAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnAppServerAPI.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutMe = "I'm admin",
                            Email = "admin1@emailcom",
                            FacebookLink = "http:facebook.com/user/123",
                            IsAdmin = true,
                            Password = "strongPassword1",
                            PhoneNumber = "+48123456789",
                            TwitterLink = "http:twitter.com/user/123"
                        },
                        new
                        {
                            Id = 2,
                            AboutMe = "I'm normal user",
                            Email = "user1@email.com",
                            FacebookLink = "http:facebook.com/user/312",
                            IsAdmin = false,
                            Password = "strongPassword2",
                            PhoneNumber = "+48987654321",
                            TwitterLink = "http:twitter.com/user/312"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
